language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- '3.6-dev'
- '3.7-dev'
install:
- pip install -r requirements/test.txt
script:
- python -m pytest --cov=chatette tests/
after_script:
- cd ~
after_success:
- codecov
deploy:
  provider: pypi
  user: SimGus
  password:
    secure: agMPtAzkeQAAs903SkUyXWDTxX40VCT5KmFItyWd+f+2D6K/SQmt0N+jPzFwNANIQRiNzdcqII7kIvPNPJZmTfu3fcVOkOFCQBWGttpUiWtmoJomGnBRIqgavADddiZWQKTGbs2siLOV85Ds3sFRN/7MxKvOe3Is4XP/0t0p9GBPWQ+Rxa9zAi84KrDUa3sWFZv9sX/D0h33E2EVZHdx4pX5LN1WGqk8EGXsVJzdqUZcqzWFpdF/A4Hk/+sjKfD28XkuXQi3rxv6KEkPo4AlbAiVSnpuv2DCpodKgqpv1IDlKlKhbIC216miXHnyXbHG3OEr0l+jbUYvGija2iierFOyjm8i3QsOIdgqvHfpJLnMBVmXejPRGrrLFFOZRPD1IejK8UdArFWaVe/wNGfihLcslgxRZ4hDZb6I4GCA41fT6uMb58yjx35Oy0VsBq+rpnncqVjf/I52atba6dXAmz2U6znouXgBtVfS6KpaEOJCIu/qIZQlfRE9w3u/pagrZYPEdmNNFhA4nDm11FIpTkLMChuFyu+LFvAhB3nVgcxllSAg8Z5xTQH5BfKb6lilqwucklGWpQm7OlDPt6VlfONoes1odSVEsRgi3sRcLJNVNh+PebyyqggZuvT26y7pMGTXqgzLJyQzbBwJ+b/un3mKpYhsUzccqDMYSYftwKw=
  on:
    tags: true
  distributions: sdist bdist_wheel
  skip_existing: true
